import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '../../component/Card/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.description}>
				</div>

				<div className={styles.center}>
					<Card char_name={"Wrong rick"} desc={"He'll never gonna give you up tho"} type="primary"/>
					<Card char_name={"Not Red rick"} desc={"He'll never gonna give you up tho"} type="secondary"/>

				</div>

				<div className={styles.grid}>

				</div>
			</main>
		</>
	)
}
